name: CD for Admin App

on:
  workflow_run:
    workflows: ["CI for Admin App"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.0' 

      - name: Extract Git commit hash
        id: vars
        run: echo "COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-5)" >> $GITHUB_ENV

      - name: Update Kubernetes deployment with new image tag
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          ls -la $HOME/.kube
          touch config
          ls -la $HOME/.kube 
          chmod 600 $HOME/.kube/config
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          ls -la $HOME/.kube
          sed -i "s|image: expotechx/admin:.*|image: expotechx/admin:${COMMIT_HASH}|" k8s/admin-app.yaml
          kubectl apply -f k8s/admin-app.yaml
          kubectl rollout status deployment admin-deploy
        shell: bash
